### ISSUE TITLE
Example 404

### ISSUE THREAD

**Issue by syifarahmat** [hiwepy/shiro-cas-spring-boot-starter#2]
Where can I read an example?
Because [https://github.com/vindell/spring-boot-starter-samples] cannot be accessed

**Comment by hiwepy** [comment]
Sorry, I haven't had time to write a separate example



At 2020-12-23 10:52:04, "Syifa Rahmat" <notifications@github.com> wrote:

Where can I read an example?
Because [https://github.com/vindell/spring-boot-starter-samples] cannot be accessed
